apiVersion: v1
kind: Service
metadata:
  name: langfuse-clickhouse
spec:
  type: ClusterIP
  selector:
    app: langfuse-clickhouse
  ports:
    - port: 8123
      targetPort: 8123
      name: http
    - port: 9000
      targetPort: 9000
      name: native

