apiVersion: v1
kind: Secret
metadata:
  name: langfuse-clickhouse-secret
type: Opaque
stringData:
  password: langfuse-clickhouse-password  # Change this to a secure password in production
  database-url: clickhouse://default:langfuse-clickhouse-password@langfuse-clickhouse:9000

