apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  access-key: minioadmin  # Change this to a secure access key in production
  secret-key: minioadmin  # Change this to a secure secret key in production

